platform :ios, '8.0'

#use_frameworks!

target 'MCObserverKit_Example' do
  pod 'MCObserverKit', :path => '../'
  pod 'MLeaksFinder', '~> 1.0.0'

  target 'MCObserverKit_Tests' do
    inherit! :search_paths

    
  end
end
